### ISSUE TITLE
Update Pod name in documentation

### ISSUE THREAD

**Issue by PhilippeCuvillier** [zendesk/connect-ios-sdk#11]
Pod name should be changed from `'Connect'` to `'ZendeskConnect'` in [Zendesk documentation](https://developer.zendesk.com/embeddables/docs/connect/ios#add-the-connect-sdk-to-swift-projects) and [Pod documentation](https://cocoapods.org/pods/ZendeskConnect).

Thanks a lot!

**Comment by tecknut** [comment]
Hey @PhilippeCuvillier that should be updated now. We just pushed out an update. 

Thanks
