### ISSUE TITLE
CocoaPods install doesn't include AdminPanel.storyboard

### ISSUE THREAD

**Issue by cwheeler42** [zendesk/connect-ios-sdk#17]
**Describe the bug**
Did a basic CocoaPods install per the instructions in the readme and when running the app and long pressing 4 fingers to bring up the Admin Panel, I get a crash because the storyboard can't be found. No storyboard file is present in any Pods/ZendeskConnect folder. We have an Obj-C project. All other CocoaPods have been fine to this point--we're not new to CocoaPods.

**To Reproduce**
1. Follow CocoaPods install instructions
2. Build and run on device
3. Hold down 4 fingers for 8 seconds
4. See error: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'AdminPanel' in bundle NSBundle

**Expected behavior**
Obviously, would not expect a crash.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OS X 10.13.6
 - Xcode 10.1

**Smartphone (please complete the following information):**
 - Device: iPhopne 
 - OS: iOS 12.1

**Additional context**

**Comment by cwheeler42** [comment]
Thought it worth mentioning that this is with the ZendeskConnect 2.0.0 SDK (latest installed by CocoaPods by default) and I was able to reproduce this simply by creating the most basic new Obj-C project in Xcode (Single View App), doing pod init for the project, adding the ZendeskConnect SDK to the podfile, and installing the pod. Just those simple steps will create a sample project that exhibits the behavior described (crash on AdminPanel because there is no Storyboard resource).

**Comment by tecknut** [comment]
Hey @cwheeler42, 

Sorry for the delay in responding to you. Thank you for bringing this to our attention. We've fixed the issue with our podspec and just pushed it up to the main specs repo. I had tested prior to publishing the new spec and could replicate the issue. I just tested against 2.0.1 and it's working.

Can you try update and let us know if it's all good on your end? 

Thanks,
Alan

**Comment by cwheeler42** [comment]
This seems to have done the trick. No more crash and the AdminPanel comes up now. Thanks for the speedy fix!

**Comment by tecknut** [comment]
No problem! I'll close this. 

Get back in touch if you have any further issues. 
Alan
