### ISSUE TITLE
Currently, Zendesk does not support for Swift 5.1.2

### ISSUE THREAD

**Issue by duydtdev** [zendesk/connect-ios-sdk#24]
Please help:
`Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9).`

**Comment by baz8080** [comment]
This is a [carthage issue](https://github.com/Carthage/Carthage/issues/2887) which has recently been solved. Please update Carthage and try again.
